INSERT INTO cliente (nome, telefone, endereco) VALUES ('Wesley', '98326174', 'Maiobão');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Carla', '98907838', 'Cohab');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Tadeu', '98899290', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Maria', '98627434', 'Cohab');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('David', '98591249', 'Anil');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('José', '98456730', 'Cohama');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('João', '98512297', 'Anil');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Josefa', '98188003', 'Cohama');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Ana', '98755304', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('França', '98302997', 'São Francisco');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Dávila', '98416128', 'Anil');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Viviana', '98871753', 'Maiobão');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Jamanta', '98485470', 'Maiobão');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Jonas', '98250014', 'Maiobão');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Batista', '98629532', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Sandra', '98123731', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Bruna', '98564047', 'São Francisco');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Lucas', '98381313', 'São Francisco');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Larissa', '98282539', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Letícia', '98730635', 'João Paulo');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Lúcio', '98333394', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Gabriel', '98157391', 'Monte Castelo');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Kim', '98844453', 'Monte Castelo');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Joana', '98647061', 'João Paulo');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Pedro', '98981483', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Eduarda', '98958895', 'Coheb');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Luciana', '98843823', 'Coheb');