INSERT INTO cidade (nome, uf, taxa) VALUES ('São Paulo', 'SP', '93');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Rio de Janeiro', 'RJ', '63');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Brasília', 'DF', '71');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Salvador', 'BA', '75');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Fortaleza', 'CE', '15');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Belo Horizonte', 'MG', '06');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Manaus', 'AM', '73');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Curitiba', 'PR', '78');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Recife', 'PE', '26');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Goiânia', 'GO', '07');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Belém', 'PA', '91');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Porto Alegre', 'RS', '70');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Guarulhos', 'SP', '49');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Campinas', 'SP', '17');
INSERT INTO cidade (nome, uf, taxa) VALUES ('São Luís', 'MA', '00');
INSERT INTO cidade (nome, uf, taxa) VALUES ('São Gonçalo', 'RJ', '86');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Maceió', 'AL', '99');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Duque de Caxias', 'RJ', '89');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Campo Grande', 'MS', '63');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Natal', 'RN', '37');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Teresina', 'PI', '79');
INSERT INTO cidade (nome, uf, taxa) VALUES ('São Bernardo do Campo', 'SP', '66');
INSERT INTO cidade (nome, uf, taxa) VALUES ('João Pessoa', 'PB', '36');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Nova Iguaçu', 'RJ', '05');
INSERT INTO cidade (nome, uf, taxa) VALUES ('São José dos Campos', 'SP', '02');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Santo André', 'SP', '68');
INSERT INTO cidade (nome, uf, taxa) VALUES ('Ribeirão Preto', 'SP', '48');