INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('7', '9', 'Computador', '2', '3345');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('1', '21', 'Celular', '3', '4408');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('25', '1', 'Caderno', '3', '2645');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('16', '7', 'Fone de Ouvido', '4', '4764');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('14', '23', 'Celular', '3', '4596');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('13', '4', 'Celular', '5', '3979');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('20', '21', 'Computador', '4', '3896');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('26', '09', 'Computador', '1', '3386');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('9', '9', 'Caderno', '3', '1628');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('13', '18', 'Caderno', '3', '1563');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('1', '18', 'Celular', '3', '1093');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('10', '23', 'Celular', '1', '3216');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('2', '8', 'Fone de Ouvido', '4', '3350');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('19', '13', 'Caderno', '1', '2935');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('21', '7', 'Caderno', '1', ' 415');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('27', '25', 'Computador', '1', '3322');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('8', '23', 'Computador', '2', '3431');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('17', '13', 'Mesa', '1', '0067');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('18', '4', 'Caneta', '4', '0461');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('3', '2', 'Celular', '1', '0282');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('20', '21', 'Celular', '5', '1370');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('14', '27', 'Sapato', '3', ' 954');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('22', '18', 'Computador', '5', '1261');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('26', '15', 'Computador', '2', '1926');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('12', '18', 'Fone de Ouvido', '2', '3786');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('3', '6', 'Celular', '4', '1836');
INSERT INTO frete (codigo_cliente, codigo_cidade, descricao, peso, valcr) VALUES ('10', '10', 'Celular', '4', '3120');