name: projetoIntegracao

on:
  workflow_dispatch:
  
  #pull_request:
  #  types: [opened, synchronize, reopened, closed]
  #  branches:
  #    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Build init
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'https://github.com/LucasFelip/springTesteIntegracao'
    needs: build
    steps:
    ## Etapa 1 - Criacao da copia do repositorio
    - name: Checkout Security
      uses: actions/checkout@v3
      
    ## Etapa 2 - Configuração JDK
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'
        
    ## Etapa 3 - Construcao e execucao dos testes
    - name: Build and run tests
      run: mvn clean install
      
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs: deploy-dev
    steps:
    - name: Run a one-line script
      run: echo Deploy Prod
