name: projetoIntegracao

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'integracaoci-dev.com'
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Deploy Dev
    - name: Setup a Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft' # See 'Supported distributions' for available options
        java-version: '17'
    - run: java HelloWorldApp.java
    
      
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'integracaoci.com'
    needs: deploy-dev
    steps:
    - name: Run a one-line script
      run: echo Deploy Prod
